# Generated by Django 4.1.3 on 2023-10-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete_by',
            field=models.DateField(null=True),
        ),
    ]
